default:
  image: ruby:2.4.2
  before_script:
    - cd reddit
    - bundle install
  services:
    - name: docker:18.09.7-dind

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_job:
  image: docker:latest
  stage: build
  tags:
    - dind
  before_script:
    - docker info
    - echo $CI_SERVER_HOST
  script:
    - echo "Build test"
    - docker pull hatterfix/otus-reddit:1.0


test_unit_job:
  stage: test
  tags:
    - docker
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

.test_integration_job:
  stage: test
  tags:
    - docker
  script:
    - echo 'Testing 2'

.deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  image: docker:19.03
  variables:
    DOCKER_HOST: tcp://docker:2375
  stage: review
  tags:
    - docker
  before_script:
    - docker info
    - echo $CI_SERVER_HOST
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker run --name reddit -d -p 9292:9292 hatterfix/otus-reddit:1.0
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
