- name: delete reddit image & container
  hosts: all
  become: true

  tasks:
    - name: check current status
      command: docker ps -a

    - name: stop reddit container
      command: docker container stop reddit

    - name: remove reddit container
      command: docker rm reddit

    - name: remove docker image reddit
      command: docker rmi hatterfix/otus-reddit:1.0
