- name: Run Gitlab CI into container
  hosts: all
  become: true

  tasks:
    - name: Copy docker-compose.yml to /srv/gitlab
      ansible.builtin.copy:
        src: /tmp/docker-compose.yml
        dest: /srv/gitlab/docker-compose.yml
        remote_src: yes

    - name: run gitlab-ci in container
      command: docker-compose up -d
      args:
        chdir: /srv/gitlab/
