version: '3.3'
networks:
  front_net:
  back_net:
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
       back_net:
        aliases:
        - post_db
        - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      -  ${UI_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - front_net
      - back_net
  # prometheus:
  #   image: ${USERNAME}/prometheus_blackbox
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--storage.tsdb.retention=1d'
  #   networks:
  #     - front_net
  #     - back_net
  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     - back_net
  # mongodb-exporter:
  #   image: bitnami/mongodb-exporter
  #   user: root
  #   environment:
  #     - MONGODB_URI=mongodb://post_db:27017
  #   networks:
  #     - back_net

  # blackbox-exporter:
  #   image: prom/blackbox-exporter:v0.22.0
  #   networks:
  #     - front_net
  #     - back_net

volumes:
    post_db:
    prometheus_data:
