name: Lint Dockerfile

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
         - dockerfile: "./docker-monolith/tmpDockerfile"
         - dockerfile: "./src/post-py/Dockerfile"
         - dockerfile: "./src/comment/Dockerfile"
         - dockerfile: "./src/ui/Dockerfile"
